services:
  - type: web
    name: cluely-fr
    env: node
    plan: free
    buildCommand: npm ci --legacy-peer-deps && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: cluely-fr-db
          property: connectionString
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: cluely-fr-db
    databaseName: cluely_fr
    user: cluely_fr_user 