services:
  - type: web
    name: coachia-app
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: coachia-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: coachia-db
    databaseName: coachia
    user: coachia_user
    plan: free 